-- ============================================================================
-- 03_MONITORING_VERIFY.SQL
-- Purpose: Test insertion, verify task execution, dbt logs, and layer flow
-- ============================================================================

USE ROLE ACCOUNTADMIN;
USE DATABASE MAVEN_CANDY_ANALYTICS;
USE SCHEMA SILVER;

-- 1. Insert test transaction into Bronze
INSERT INTO MAVEN_CANDY_ANALYTICS.BRONZE.RAW_CANDY_SALES (
    ROW_ID, ORDER_ID, ORDER_DATE, SHIP_DATE, SHIP_MODE, CUSTOMER_ID, 
    COUNTRY_REGION, CITY, STATE_PROVINCE, POSTAL_CODE, DIVISION, 
    REGION, PRODUCT_ID, PRODUCT_NAME, SALES, UNITS, GROSS_PROFIT, COST
) VALUES (
    888111, 'ORD-AUTO-01', '2026-09-29', '2026-09-30', 'Standard Class', 
    'CUST-AUTO', 'United States', 'Chicago', 'Illinois', '60601', 
    'Candy', 'Central', 'PRD-AUTO', 'Automated Task Test Item', 300.00, 100, 100.00, 200.00
);

-- 2. Query Task execution history
SELECT NAME, STATE, SCHEDULED_TIME, COMPLETED_TIME, QUERY_ID, ERROR_MESSAGE
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
    TASK_NAME => 'TSK_RUN_DBT_BUILD', 
    RESULT_LIMIT => 5
))
ORDER BY SCHEDULED_TIME DESC;

-- 3. Retrieve Native dbt Log (Pass specific QUERY_ID string from history query)
-- SELECT SYSTEM$GET_DBT_LOG('<INSERT_QUERY_ID_HERE>');

-- 4. Verify propagation across Medallion layers
SELECT '1_SILVER_STAGING' AS LAYER, ROW_ID, ORDER_ID, PRODUCT_NAME, SALES, UNITS 
FROM MAVEN_CANDY_ANALYTICS.SILVER.STG_RAW_SALES WHERE ROW_ID = 888111;

SELECT '2_SILVER_FACT' AS LAYER, ROW_ID, ORDER_ID, PRODUCT_NAME, SALES, UNITS 
FROM MAVEN_CANDY_ANALYTICS.SILVER.FCT_CANDY_SALES WHERE ROW_ID = 888111;

SELECT '3_GOLD_SUMMARY' AS LAYER, ORDER_DATE, TOTAL_ORDERS, TOTAL_UNITS_SOLD, TOTAL_REVENUE 
FROM MAVEN_CANDY_ANALYTICS.GOLD.FCT_SALES_SUMMARY WHERE ORDER_DATE = '2026-09-29';

SELECT '4_STREAM_CLEARED' AS CHECK_POINT, COUNT(*) AS PENDING_ROWS 
FROM MAVEN_CANDY_ANALYTICS.BRONZE.STR_RAW_CANDY_SALES;
